---
title: "ForestGEO Value Generator"
author: "J. M. Rodríguez"
date: "12023-06-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Setup
Setting up necessary packages, and locations for the files. The location for retrieving scripts is:

```{r cars, echo = 0}
# Setting locations:
loc_Gdr <- "G:/Shared drives/NASA_ForestScaling/LifeHistoryStrats"
loc_data1 <- paste0(loc_Gdr, "/data/ForestGEO/processed/canopy_assign/")
loc_data2 <- paste0(loc_Gdr, "/data/ForestGEO/taxa/")
loc_out1 <- paste0(loc_Gdr, "/outputs/")
#loc_out1 <- paste0("C:/Users/juan.m.rodriguez/Downloads/", "") # for setting
  # setting these to dump out into my downloads folder so I can check that this
  # is working properly

# Bringing in the packages:
packages <- c("tidyverse", "magrittr", "lubridate", "rstudioapi")
invisible(lapply(packages, library, character.only = T))


# Setting/finding location of the script, so that the WD is automatically
# within GITHub local copy location.
setwd(dirname(rstudioapi::getSourceEditorContext()$path))

print(getwd())
print(list.files())

# Bring in commonly used functions
#source("scripts/00_Functions.R")


```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
